travis:
  secure:
    BINSTAR_TOKEN: mnQIgBi/12fLI4OqdzhPo8kkGYTSCeD1kGs7DEDjr7SKbD83WWc8BhwLTI6fOT5BgikP9v4invAtoi09l3irR46j0i1JYEbtXuY2u5qwV3I8xww+1LNf928uDi6VqQNQlDxce40KMk73mMCV/NpC4p5IW3CHVpocTSMc4KOqJeAz2pdLBbR2ALic115riozLR8jatjSUFvE5IZaAesOaykO4nCK0poV0HP05bMm/uqnfQwZp/fcTYMsM/jaUQTZZB917M6S72aLaBUKw+xZoqymkTTlOD/VF2SSEqA7BvJExDJM6gZGRn6N3i3YL7XUv6Wi55TqrepSbSiLLsa11cf0ZEZmeCSora1f3DDsXOElmqyAtayQyBdyu9roQ11sjSaQe0jAwyjKLX0K6RLs8DUvncv7qmayi7YlDBpsh7RL78+WU20t77v6K+i2+DdkPKYYzc40DWkr96LtVB4Vc/EuiWlvDzGrMPvR7RaRmshCdKPOxqBQzbwDoHteXPsG+rXRh/Gm7lsnFTZfvQY3O2UjoPQ17RqtcMyow6GSG+V1rIJi88l7W9BKVbxdjbcU7xcEZhgAYMK7W53WxObSooBlBZzlhxO4a7saAJ4Vr+zwTI1fGliI/slmCQFMX9r2MidRijAtheyShI7z80/O4td/unuFdZYqWhFtaFRn44RA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
